# Site settings
author: Jonathan Swankie
title: 
header-img: img/home-bg.png
email: jonathan@swankie.net
copyright_name: Jonathan Swankie
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  spikeyball

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
